// ─────────────────────────────────────────────────────────────
// Domain types — kept narrow so Firestore docs map 1:1
// ─────────────────────────────────────────────────────────────

export type CategoryIcon =
  | "starters"
  | "mains"
  | "burgers"
  | "salads"
  | "drinks"
  | "desserts";

export interface Category {
  id: string;
  name: string;
  order: number;
  icon: CategoryIcon;
}

export interface MenuItem {
  id: string;
  categoryId: string;
  name: string;
  price: number;
  description: string;
  /** Hero image URL (WebP recommended). */
  imageUrl: string;
  /** GLB for Android / desktop / WebXR. Optional — items without a model hide the AR CTA. */
  modelUrl?: string;
  /** USDZ for iOS Quick Look. */
  usdzUrl?: string;
  calories: number;
  ingredients: string[];
  /** Editor's pick — drives the recommend ribbon. */
  isRecommended?: boolean;
  /** Spice level 0-3, drives heat tag dots. */
  heat?: 0 | 1 | 2 | 3;
}

export interface TastingNote {
  /** 2-line gourmet description from Gemini. */
  description: string;
  /** A short pairing suggestion (drink / side). */
  pairing?: string;
  /** Macro highlights generated by AI. */
  highlights?: string[];
}
